management:
  endpoint:
    metrics:
      enabled: true
  metrics.export.graphite:
    host: graphite
    port: 2004
    step: 10s
  endpoints:
    web:
      exposure:
        include: ["metrics", "info", "health"]
spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
server:
  tomcat:
    mbeanregistry:
      enabled: true